name: test this action

on:
  push:
    paths:
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run this action
      uses: zhuorg/dockercontainer_action@master
